version: '3'

services:
  speedtest_collector:
    build: .
    expose:
      - 3000

  prometheus:
    image: prom/prometheus
    command: --log.level=debug
    volumes:
      - ./prometheus.yml:/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000